
services:
  db:
      image: postgres:17
      container_name: postgresChat
      restart: unless-stopped
      environment:
        POSTGRES_DB: chat
        POSTGRES_USER: chat
        POSTGRES_PASSWORD: chatPassword
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U chat -d chat"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - pgChat2Data:/var/lib/postgresql/data

volumes:
  pgChat2Data: